spring:
  resources:
    static-locations: classpath:/templates/,classpath:/static/

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/country?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

